name: Build
# Tests if the website will build so we don't merge in bad 

on:
  pull_request:
    branches: [ * ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Build Site
        run: |
          pnpm i
          pnpm run build