# This is a basic workflow to help you get started with Actions

name: deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DO_IP }} >> ~/.ssh/known_hosts

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Build Site
        run: |
          pnpm i
          pnpm run build
          ls

      - name: Upload To Droplet
        run: |
          rsync -avz --delete --no-times --no-o --no-g --no-perms ./build/ james@${{ secrets.DO_IP }}:/home/learn/www/
